name: Release and Push to NuGet

on:
  push:
    tags:
        - '*'
  workflow_dispatch:

jobs:
  build:
    uses: gaviny82/AppSettingsManagement/.github/workflows/build-linux.yml@main
  
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: packages
        path: ./artifacts

    # Checkout the code if run manually to allow tag to be obtained
    - name: Checkout code
      uses: actions/checkout@v3
      if: ${{ github.event_name }} == 'push'
      with:
        fetch-depth: 0 # Required to get all git history

    # Replace refs/tags/ with empty string from github.ref if a tag is pushed, otherwise use the latest tag
    - name: Get Tag
      id: get_tag
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        else
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifacts/*
        name: Release ${{ steps.get_tag.outputs.tag }}
        tag_name: ${{ steps.get_tag.outputs.tag }}
        generate_release_notes: true
        draft: true
        prerelease: true