name: Release and Push to NuGet

on:
  push:
    tags:
        - '*'
  workflow_dispatch:

jobs:
  build:
    uses: gaviny82/AppSettingsManagement/.github/workflows/build-linux.yml@main
  
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: packages
        path: ./artifacts

    # Replace refs/tags/ with empty string if a tag is pushed, otherwise use the latest tag
    - name: Get version number
      id: get_version
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        else
          echo ::set-output name=version::$(git describe --tags `git rev-list --tags --max-count=1`)
        fi

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./artifacts/*
        name: Release ${{ steps.get_version.outputs.version }}
        tag_name: ${{ github.ref }}
        generate_release_notes: true
        draft: true
        prerelease: true