name: Release and Push to NuGet

on:
  push:
    tags:
        - '*'
  workflow_dispatch:

jobs:
  build:
    uses: gaviny82/AppSettingsManagement/.github/workflows/build-linux.yml@main
  
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 7.0.x

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: packages
        path: ./artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: Body
        draft: false
        prerelease: true